export const groupConstant = {
    FETCH_GROUPS_REQUEST: "FETCH_GROUPS_REQUEST",
    FETCH_GROUPS_SUCCESS: "FETCH_GROUPS_SUCCESS",
    FETCH_GROUPS_FAILURE: "FETCH_GROUPS_FAILURE",

    ADD_GROUP_REQUEST: "ADD_GROUP_REQUEST",
    ADD_GROUP_SUCCESS: "ADD_GROUP_SUCCESS",
    ADD_GROUP_FAILURE: "ADD_GROUP_FAILURE",

    ADD_MEMBER_REQUEST: 'ADD_MEMBER_REQUEST',
    ADD_MEMBER_SUCCESS: 'ADD_MEMBER_SUCCESS',
    ADD_MEMBER_FAILURE: 'ADD_MEMBER_FAILURE',

    GET_MEMBERS_REQUEST: 'GET_MEMBERS_REQUEST',
    GET_MEMBERS_SUCCESS: 'GET_MEMBERS_SUCCESS',
    GET_MEMBERS_FAILURE: 'GET_MEMBERS_FAILURE',

    FETCH_GROUP_DETAIL_REQUEST: 'FETCH_GROUP_DETAIL_REQUEST',
    FETCH_GROUP_DETAIL_SUCCESS: 'FETCH_GROUP_DETAIL_SUCCESS',

    FETCH_GROUP_POSTS_REQUEST: 'FETCH_GROUP_POSTS_REQUEST',
    FETCH_GROUP_POSTS_SUCCESS: 'FETCH_GROUP_POSTS_SUCCESS',

    ADD_GROUP_POST_REQUEST: "ADD_GROUP_POST_REQUEST",
    ADD_GROUP_POST_SUCCESS: "ADD_GROUP_POST_SUCCESS",
    ADD_GROUP_POST_FAILURE: "ADD_GROUP_POST_FAILURE",

    CHANGE_COVER_REQUEST: "CHANGE_COVER_REQUEST",
    CHANGE_COVER_SUCCESS: "CHANGE_COVER_SUCCESS",
    CHANGE_COVER_FAILURE: "CHANGE_COVER_FAILURE",

    UPDATE_GROUP_REQUEST: "UPDATE_GROUP_REQUEST",
    UPDATE_GROUP_SUCCESS: "UPDATE_GROUP_SUCCESS",
    UPDATE_GROUP_FAILURE: "UPDATE_GROUP_FAILURE",
};
